language: java

dist: xenial

services:
   - xvbf
   - docker

jdk: openjdk8

addons:
   sonarcloud:
      organization: "alessandrolemmo"
      token: $SONAR_TOKEN

install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache


script:
- mvn -f airport-management/pom.xml clean verify -Pjacoco coveralls:report sonar:sonar






